before_install:
  - sudo apt-get update --fix-missing
  
install:
  - sudo apt-get install -y ffmpeg libavcodec-extra-53
  - bundle install
  
language: ruby

rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0